name: chemprop
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - pytorch::pytorch
  - pytorch::torchaudio
  - pytorch::torchvision
  - astartes[molecules]
  - aimsim
  - lightning
  - numpy
  - pandas
  - rdkit
  - scikit-learn
  - scipy
