name: chemprop
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - comm=0.2.2
  - debugpy=1.8.1
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - ipykernel=6.29.3
  - ipython=8.22.2
  - jedi=0.19.1
  - jupyter_client=8.6.1
  - jupyter_core=5.7.2
  - ld_impl_linux-64=2.40
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgomp=13.2.0
  - libnsl=2.0.1
  - libsodium=1.0.18
  - libsqlite=3.45.2
  - libstdcxx-ng=13.2.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.2.13
  - matplotlib-inline=0.1.6
  - ncurses=6.4.20240210
  - nest-asyncio=1.6.0
  - openssl=3.2.1
  - packaging=24.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.0
  - platformdirs=4.2.0
  - prompt-toolkit=3.0.42
  - psutil=5.9.8
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.17.2
  - python=3.11.8
  - python_abi=3.11
  - pyzmq=25.1.2
  - readline=8.2
  - setuptools=69.2.0
  - six=1.16.0
  - stack_data=0.6.2
  - tk=8.6.13
  - tornado=6.4
  - traitlets=5.14.2
  - typing_extensions=4.11.0
  - wcwidth=0.2.13
  - wheel=0.43.0
  - xz=5.2.6
  - zeromq=4.3.5
  - zipp=3.17.0
  - pip:
      - aimsim-core==2.1.3
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - astartes==1.2.2
      - attrs==23.2.0
      - chemprop==2.0.0rc1
      - dill==0.3.8
      - filelock==3.13.3
      - frozenlist==1.4.1
      - fsspec==2024.3.1
      - idna==3.6
      - jinja2==3.1.3
      - joblib==1.4.0
      - lightning==2.2.1
      - lightning-utilities==0.11.2
      - markupsafe==2.1.5
      - mhfp==1.9.6
      - mordredcommunity==2.0.5
      - mpmath==1.3.0
      - multidict==6.0.5
      - multiprocess==0.70.16
      - networkx==3.3
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - padelpy==0.1.16
      - pandas==2.2.1
      - pillow==10.3.0
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.2.1
      - pytz==2024.1
      - pyyaml==6.0.1
      - rdkit==2023.9.5
      - scikit-learn==1.4.1.post1
      - scikit-learn-extra==0.3.0
      - scipy==1.13.0
      - sympy==1.12
      - tabulate==0.9.0
      - threadpoolctl==3.4.0
      - torch==2.2.2
      - torchmetrics==1.3.2
      - tqdm==4.66.2
      - triton==2.2.0
      - tzdata==2024.1
      - yarl==1.9.4
